// Generated by CoffeeScript 1.8.0
(function() {
  var assert, eps, expect, _ref;

  _ref = require("chai"), expect = _ref.expect, assert = _ref.assert;

  require("../src/toms708/bratio.js");

  eps = 0.0000000000000001;

  describe("S.Bratio", function() {
    return it("fpser is working", function() {
      var bratio, w;
      bratio = new S.Bratio(0.9e-01, 1.0, 0.5e-16);
      w = bratio.getw();
      expect(w).to.be.closeTo(0, eps);
      return expect(1 - w).to.be.closeTo(1, eps);
    });
  });

}).call(this);
